In [ ]:
import numpy as np

In [ ]:
def determinant(matrix):    # Base case: if the matrix is 1x1, return its single element
    if len(matrix) == 1:        return matrix[0][0]
        # Base case: if the matrix is 2x2, return the determinant directly
    if len(matrix) == 2:        return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    det = 0
    for j in range(len(matrix[0])):  # Iterate over the columns        # Exclude the first row and the jth column
        sub_matrix = [row[:j] + row[j+1:] for row in matrix[1:]]        # Recursive call to compute the determinant of the sub-matrix
        det += (-1) ** j * matrix[0][j] * determinant(sub_matrix)
    return det

In [ ]:
def matrix_multiply(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        raise ValueError("Number of columns in the first matrix must be equal to the number of rows in the second matrix.")

    result = []
    for i in range(len(matrix1)):
        row = []
        for j in range(len(matrix2[0])):
            element = 0
            for k in range(len(matrix2)):
                element += matrix1[i][k] * matrix2[k][j]
            row.append(element)
        result.append(row)

    return result

In [ ]:
def transpose(matrix):
    # Function to transpose a matrix
    rows = len(matrix)
    cols = len(matrix[0])
    transposed = [[0] * rows for _ in range(cols)]
    for i in range(rows):
        for j in range(cols):
            transposed[j][i] = matrix[i][j]
    return transposed

In [ ]:
def matrix_minor(matrix, row, col):
    # Function to find the minor of a matrix
    return [row[:col] + row[col+1:] for row in (matrix[:row] + matrix[row+1:])]

def cofactor(matrix):
    # Function to find the cofactor of a matrix
    cofactor_matrix = []
    for row in range(len(matrix)):
        cofactor_row = []
        for col in range(len(matrix)):
            minor = matrix_minor(matrix, row, col)
            cofactor_row.append(((-1) ** (row + col)) * determinant(minor))
        cofactor_matrix.append(cofactor_row)
    return cofactor_matrix

In [ ]:
def inverse(matrix):
    # Function to find the inverse of a matrix
    det = determinant(matrix)
    if det == 0:
        return None  # Matrix is singular, no inverse exists
    cofactor_mat = cofactor(matrix)
    transposed_cofactor = transpose(cofactor_mat)
    inverse_mat = [[element / det for element in row] for row in transposed_cofactor]
    return inverse_mat

In [ ]:
A = np.array([[1, 3, 3],
             [-3, 5, 3],
             [3, 3, 1]])
dim = len(A)
eig_val, eig_vec = np.linalg.eig(A)

P = eig_vec
P = P.tolist()

D = np.eye(dim)
for i in range(dim):
    D[i][i] = eig_val[i]

P_inv = inverse(P)

result = matrix_multiply(P, matrix_multiply(D, P_inv))

def round_matrix(matrix, decimal_places=2):
    rounded_matrix = [[round(element, decimal_places) for element in row] for row in matrix]
    return rounded_matrix

result = np.array(round_matrix(result))

# A = PDP^-1

In [ ]:
print(A)

[[ 1  3  3]
 [-3  5  3]
 [ 3  3  1]]


In [ ]:
print(result)

[[ 1.  3.  3.]
 [-3.  5.  3.]
 [ 3.  3.  1.]]


# Columns of P are independent

In [ ]:
x = determinant(result.tolist())
print(x)

-40.0
