In [9]:
import numpy as np


In [15]:
def matrix_multiply(matrix1, matrix2):
    if len(matrix1[0]) != len(matrix2):
        print("Number of columns in the first matrix and the number of rows in the second matrix should be same")
        return

    result = []
    for i in range(len(matrix1)): # Iterate through each row of the first matrix
        row = []
        for j in range(len(matrix2[0])): # Iterate through each column of the second matrix
            element = 0
            # Iterate through each element of the corresponding row in the first matrix
            # and the corresponding column in the second matrix, and compute the dot product
            for k in range(len(matrix2)):
                element += matrix1[i][k] * matrix2[k][j]
            row.append(element)
        result.append(row)

    return result

In [5]:
def determinant(matrix):
    if len(matrix) == 1: # If the matrix is 1x1, return its single element
      return matrix[0][0]
    if len(matrix) == 2: # If the matrix is 2x2, return the determinant directly
      return matrix[0][0] * matrix[1][1] - matrix[0][1] * matrix[1][0]
    det = 0
    for j in range(len(matrix[0])):  # Iterate over the columns
        sub_matrix = [row[:j] + row[j+1:] for row in matrix[1:]] # Exclude the first row and the jth column
        det += (-1) ** j * matrix[0][j] * determinant(sub_matrix) # Find determinant
    return det

In [6]:
def transpose(matrix):
    rows = len(matrix)
    cols = len(matrix[0])
    transposed = [[0] * rows for _ in range(cols)]
    for i in range(rows):
        for j in range(cols):
            transposed[j][i] = matrix[i][j]
    return transposed

In [7]:
def matrix_minor(matrix, row, col):
    # Function to find the minor of a matrix
    return [row[:col] + row[col+1:] for row in (matrix[:row] + matrix[row+1:])]

def adjoint(matrix):
    adjoint_matrix = []
    for row in range(len(matrix)): # Iterate through each row of the matrix
        cofactor_row = []
        for col in range(len(matrix)):
            minor = matrix_minor(matrix, row, col) # Exclude the specified row and column
            cofactor_row.append(((-1) ** (row + col)) * determinant(minor))
        adjoint_matrix.append(cofactor_row)
    return adjoint_matrix

##A^-1 = (adj A)/(det A)

In [8]:
def inverse(matrix):
    # Function to find the inverse of a matrix
    det = determinant(matrix)
    if det == 0:
        return None  # Matrix is singular, no inverse exists
    adjoint_A = adjoint(matrix)
    transposed_cofactor = transpose(adjoint_A)
    inverse_mat = [[element / det for element in row] for row in transposed_cofactor]
    return inverse_mat

In [17]:
A = [[0,1,2],[1,0,3],[4,-3,8]]
print(np.array(A))
A_inv = inverse(A)
print(np.array(A_inv))

[[ 0  1  2]
 [ 1  0  3]
 [ 4 -3  8]]
[[-4.5  7.  -1.5]
 [-2.   4.  -1. ]
 [ 1.5 -2.   0.5]]


In [18]:
result = matrix_multiply(A,A_inv)
print(np.array(result))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
