In [12]:
import numpy as np
import sympy # To find RREF

In [13]:
# Define the matrix A
A = np.array([[2, 1, 0], [1, 3, -1], [0, -1, 4]])

In [14]:
# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues)
print(eigenvectors)

[1.26794919 3.         4.73205081]
[[-0.78867513 -0.57735027 -0.21132487]
 [ 0.57735027 -0.57735027 -0.57735027]
 [ 0.21132487 -0.57735027  0.78867513]]


In [16]:
# Separate eigenvectors corresponding to distinct eigenvalues
distinct_eigenvalues = np.unique(eigenvalues)
print(distinct_eigenvalues)

[1.26794919 3.         4.73205081]


In [26]:
if len(distinct_eigenvalues) != len(eigenvalues):
    print("Eigenvalues are not distinct.")
else:
    print("Eigenvalues are distinct.")
    # Form matrix with eigenvectors corresponding to distinct eigenvalues
    eigenvectors_matrix = np.column_stack([eigenvectors[:,i] for i in range(len(eigenvalues))])

    # Convert matrix to RREF
    rref, pivot = sympy.Matrix(eigenvectors_matrix).rref()
    # Check if RREF has full rank
    if len(pivot) == len(distinct_eigenvalues):
        print("Eigenvectors corresponding to distinct eigenvalues are independent.")
    else:
        print("Eigenvectors corresponding to distinct eigenvalues are dependent.")

Eigenvalues are distinct.
Eigenvectors corresponding to distinct eigenvalues are independent.
